### ISSUE TITLE
Web版の日本語が文字化けする

### ISSUE THREAD

**Issue by Blue-Tone** [makewitharduino/makewitharduino.github.io#1]
http://code.makewitharduino.com/?lang=ja

Mac+Chrome
Win10+Chrome
で発生している。

Win10のChromeアプリでは、文字化けせずOK。

**Comment by okhiroyuki** [comment]
@Blue-Tone 
自分のところだと文字化けしてないですね。

ChromeのVersionとかが影響してます？
ちなみに、私は ` 63.0.3239.108` でした。

エビデンス（画像キャプチャーなど）があると助かります。

![blocklyduino 2017-12-28 14-08-16](https://user-images.githubusercontent.com/23309/34400839-b68cc3be-ebd8-11e7-8dd1-ea30d93b047c.png)

**Comment by Blue-Tone** [comment]
![blocklyduino](https://user-images.githubusercontent.com/18328371/34401127-d3b17536-ebdb-11e7-961b-df47ebc9f930.jpg)

Win10でChrome バージョン: 63.0.3239.108（Official Build） （64 ビット）

他では起きてないということは、環境が怪しいですね。
ブラウザの文字コード等の設定を確認してみます。

**Comment by okhiroyuki** [comment]
ありがとうございます。
また、環境などわかりましたら、教えてください。

**Comment by Blue-Tone** [comment]
[Chrome 拡張機能 テキストエンコーディング](https://chrome.google.com/webstore/detail/set-character-encoding/bpojelgakakmcfmjfilgdlmhefphglae/related?utm_source=chrome-app-launcher-info-dialog)
でUTF-８指定したら、文字化け治りました。
S-JIS指定で同じ化け方するので、S-JISで判定しちゃっているようです。

Developper toolでは`<meta charset="utf-8">`があるのですが、
ページのソースを表示では、`<meta charset="utf-8">`が無いですね。
名前を付けて保存をすると、htmlファイルには、charset=Shift_JIS"と記述がありました。

**Comment by Blue-Tone** [comment]
index.htmlに`<meta charset="utf-8">`を追加すると、文字化けしにくくなるかもと思いましたが、いかがでしょうか？

**Comment by okhiroyuki** [comment]
了解です！いいと思います。

**Comment by Blue-Tone** [comment]
ローカルで再現、修正して、改善確認までできました。
プルリク出したので、ご確認お願いします。
GitHubは初プルリクなので、お作法間違っているところあれば、教えてください。

**Comment by okhiroyuki** [comment]
@Blue-Tone 
こちらプルリクをマージして、アップしました。
なお、自分でも忘れていたのですが、index.html は最終的な出力結果となっており、実は下記のような生成方法をとります。

1. base.htmlを編集
2. python joint.py
3. index.htmlが更新

ちょっとChrome版との使い回しで上記のような処理をしています。
もし、python joint.py でエラーが吐かれた場合は、おそらくlxmlライブラリがないということなので、

>pip install lxml

してください。

というわけで、一旦こちら動作確認いただけたら、クローズしてくださいm(__)m

**Comment by Blue-Tone** [comment]
python joint.pyで生成したファイルで動作確認OKでした。
